version: '3'
services:
  broker:
    build: .
    ports:
      - "1883:1883"
      - "8443:8443"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
    volumes:
      - .:/code
    env_file:
      - ${NODE_ENV}.env
  redis:
    image: "redis:alpine"