version: '3'
services:
  broker:
    build: .
    ports:
      - "1883:1883"
      - "8083:8083"
    volumes:
      - .:/code
    env_file:
      - ${NODE_ENV}.env
  redis:
    image: "redis:alpine"